# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import schedule_pb2 as schedule__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_all_schedule = channel.unary_unary(
                '/Schedule/get_all_schedule',
                request_serializer=schedule__pb2.Empty.SerializeToString,
                response_deserializer=schedule__pb2.AllSchedule.FromString,
                _registered_method=True)
        self.get_schedule_bydate = channel.unary_unary(
                '/Schedule/get_schedule_bydate',
                request_serializer=schedule__pb2.Date.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)
        self.get_dates_bymovieid = channel.unary_unary(
                '/Schedule/get_dates_bymovieid',
                request_serializer=schedule__pb2.MovieId.SerializeToString,
                response_deserializer=schedule__pb2.DatesList.FromString,
                _registered_method=True)
        self.schedule_movie = channel.unary_unary(
                '/Schedule/schedule_movie',
                request_serializer=schedule__pb2.ScheduledMovie.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleData.FromString,
                _registered_method=True)
        self.unschedule_movie = channel.unary_unary(
                '/Schedule/unschedule_movie',
                request_serializer=schedule__pb2.ScheduledMovie.SerializeToString,
                response_deserializer=schedule__pb2.ScheduledMovie.FromString,
                _registered_method=True)
        self.delete_movie_from_schedule = channel.unary_unary(
                '/Schedule/delete_movie_from_schedule',
                request_serializer=schedule__pb2.MovieId.SerializeToString,
                response_deserializer=schedule__pb2.DatesList.FromString,
                _registered_method=True)
        self.delete_date_from_schedule = channel.unary_unary(
                '/Schedule/delete_date_from_schedule',
                request_serializer=schedule__pb2.Date.SerializeToString,
                response_deserializer=schedule__pb2.MoviesList.FromString,
                _registered_method=True)


class ScheduleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_all_schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_schedule_bydate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_dates_bymovieid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def schedule_movie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unschedule_movie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_movie_from_schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_date_from_schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_all_schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_schedule,
                    request_deserializer=schedule__pb2.Empty.FromString,
                    response_serializer=schedule__pb2.AllSchedule.SerializeToString,
            ),
            'get_schedule_bydate': grpc.unary_unary_rpc_method_handler(
                    servicer.get_schedule_bydate,
                    request_deserializer=schedule__pb2.Date.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
            'get_dates_bymovieid': grpc.unary_unary_rpc_method_handler(
                    servicer.get_dates_bymovieid,
                    request_deserializer=schedule__pb2.MovieId.FromString,
                    response_serializer=schedule__pb2.DatesList.SerializeToString,
            ),
            'schedule_movie': grpc.unary_unary_rpc_method_handler(
                    servicer.schedule_movie,
                    request_deserializer=schedule__pb2.ScheduledMovie.FromString,
                    response_serializer=schedule__pb2.ScheduleData.SerializeToString,
            ),
            'unschedule_movie': grpc.unary_unary_rpc_method_handler(
                    servicer.unschedule_movie,
                    request_deserializer=schedule__pb2.ScheduledMovie.FromString,
                    response_serializer=schedule__pb2.ScheduledMovie.SerializeToString,
            ),
            'delete_movie_from_schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_movie_from_schedule,
                    request_deserializer=schedule__pb2.MovieId.FromString,
                    response_serializer=schedule__pb2.DatesList.SerializeToString,
            ),
            'delete_date_from_schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_date_from_schedule,
                    request_deserializer=schedule__pb2.Date.FromString,
                    response_serializer=schedule__pb2.MoviesList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Schedule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Schedule', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Schedule(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_all_schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/get_all_schedule',
            schedule__pb2.Empty.SerializeToString,
            schedule__pb2.AllSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_schedule_bydate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/get_schedule_bydate',
            schedule__pb2.Date.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_dates_bymovieid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/get_dates_bymovieid',
            schedule__pb2.MovieId.SerializeToString,
            schedule__pb2.DatesList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def schedule_movie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/schedule_movie',
            schedule__pb2.ScheduledMovie.SerializeToString,
            schedule__pb2.ScheduleData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unschedule_movie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/unschedule_movie',
            schedule__pb2.ScheduledMovie.SerializeToString,
            schedule__pb2.ScheduledMovie.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_movie_from_schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/delete_movie_from_schedule',
            schedule__pb2.MovieId.SerializeToString,
            schedule__pb2.DatesList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_date_from_schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Schedule/delete_date_from_schedule',
            schedule__pb2.Date.SerializeToString,
            schedule__pb2.MoviesList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
